### ISSUE TITLE
Document compatible `rewrite-maven-plugin` and `rewrite-gradle-plugin` on release for quarkus-updates

### ISSUE THREAD

**Issue by gsmet** [openrewrite/rewrite-recipe-bom#23]
As part of the `quarkus-updates` project, we have been struggling a bit to find a setup that would actually reflect the current version used by the Maven plugin and the Gradle plugin.

Typically, when developing our recipes and tests, we want to make sure that we are using the version of the rewrite-bom that is used in the Maven plugin - and ideally it would be the same one used in the Gradle plugin or we will have some discrepancies.

And similarly, for the Gradle plugin.

A good example of this issue is that a new version of the Maven plugin was released yesterday, apparently together with the core project but the Maven plugin is still referencing `8.11.3`, while the core project (with I think the fix I wanted) is at `8.11.5`.

I can enforce `8.11.5` in my project but when running the Maven plugin, the jars around will be at `8.11.3` thus not having the fix.

I was wondering if there was a good strategy to actually make sure that we are using consistent versioning, apart from manually checking each update?

Also was it a mistake that `5.17.0` of the Maven plugin is pointing to `8.11.3` and not `8.11.5`?

**Comment by timtebeek** [comment]
I've renamed and moved this issue to reflect the changed scope; we're revising our release process and will plead for this to make it in.

**Comment by crankydillo** [comment]
I'm pretty sure the ask here reflects what just happened to use.  [This patch release](https://github.com/openrewrite/rewrite-maven-plugin/compare/v5.43.1...v5.43.2) brought in [this patch-released change](https://github.com/openrewrite/rewrite/pull/4592), which is breaking for us (for various reasons we needed to use Java constructor for instantiation).

Our build uses the recipe-bom, which is currently coupled with a rewrite-maven version that does not have this change.  So our build succeeds even when keeping up to date.  So far, we have been guiding our users to stay current with rewrite-maven-plugin patch releases, but that broke us because some of our recipes just stopped getting included.  What makes things worse is they are more or less silently excluded ([code](https://github.com/openrewrite/rewrite/blob/0b7ecf517d585e595aaa14bf96fcc879adfb969a/rewrite-core/src/main/java/org/openrewrite/config/ClasspathScanningLoader.java#L178)).

So +1 on seeing a compatibility matrix.  Additionally, is there any thought to delaying the Maven plugin release until after this BOM is released?

**Comment by timtebeek** [comment]
Ah sorry to hear! The compatibility matrix is pretty much every release of rewrite-recipe-bom that's listed here:
https://github.com/openrewrite/rewrite-recipe-bom/releases
Those are the versions that were released together, and recommended to be run together.

We roll up all the changes over the past two weeks into new releases on a schedule; the next one is slated for tomorrow to flush out any of these issues.

You're right in pointing out that `.patch` releases of the Maven plugin might pick up a newer OpenRewrite release that does not play well with older recipe modules. For those cases where you want to be on the latest we also have [our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions), to carry you over until the next release.

We of course never intend to break things, and to stay predictable; that's why every two weeks you get new `.minor` versions of OpenRewrite and the plugins, and any modules that were changed. The problems you're seeing here are unique to `.patch` versions of the plugins, so you can ignore those if needed.

On our end we do need `.patch` versions of the plugins to be able to bring changes to our users through Moderne, which is why you're seeing these releases at all. They'd only fall within the two week window until the next release though.

**Comment by crankydillo** [comment]
Ah, I missed that rewrite-maven-plugin is somehow managed in this bom, unless I'm misreading [your release notes](https://github.com/openrewrite/rewrite-recipe-bom/releases/tag/v2.21.1).  I think this project uses gradle-magic I'm unaware of:)

**Comment by timtebeek** [comment]
> Ah, I missed that rewrite-maven-plugin is somehow managed in this bom, unless I'm misreading [your release notes](https://github.com/openrewrite/rewrite-recipe-bom/releases/tag/v2.21.1). I think this project uses gradle-magic I'm unaware of:)

It's not as much managed (no such mechanism that I'm aware of) as it is released together and announced in tandem, such that there's always a combination that will work well. We of course recommend the latest based on what's [listed here](https://github.com/openrewrite/rewrite-recipe-bom/releases), but welcome to pick any other aligned versions from there.

**Comment by timtebeek** [comment]
We've now automated the release process to document these compatible versions automatically:
https://github.com/openrewrite/rewrite-recipe-bom/releases/tag/v2.23.2

Thanks for the nudges!
